### PR TITLE
Add support for a config path

### PR DESCRIPTION
**Pull request by Edward-Lombe**
Lets you specify a file path to a `redis.conf` file which will be used for the servers config

### CODE REVIEW

**Comment by BrandonZacharie** [comment]
Thanks for the contribution! Travis is not yet configured but he's active. Allow me some time to get him passing before reviewing this.

**Comment by Edward-Lombe** [comment]
Let me know if there is anything I can do to help 👍

**Comment by jhanzo** [comment]
👍  for this PR, any travis update for merging ? Thx a lot guys 😄

**Comment by BrandonZacharie** [comment]
Travis is up and I'm adding support for confs this weekend.

**Comment by BrandonZacharie** [comment]
This is available as 0.2.0 1fc7f136c02e2871664f1f9afa85e240d560ac64.

**Pull request closed without merging**
